### ISSUE TITLE
lichess.org bot issues

### ISSUE THREAD

**Issue by vibranium21** [QueensGambit/CrazyAra#135]
i tried to use crazyara for lichess bot but even with the weights files in engines folder it didnt work.

**Comment by QueensGambit** [comment]
Hello @vibranium21 ,

did you already check the information provided here?
* https://github.com/QueensGambit/CrazyAra/wiki/Setting-up-CrazyAra-as-a-Lichess-BOT
* Something wrong with lichess-bot program (https://github.com/QueensGambit/CrazyAra/issues/40)

After you managed to get it to run, feel free to join the [All the Ara's](https://lichess.org/team/all-the-aras) bots team.

**Comment by vibranium21** [comment]
Thank you, I am looking forward to testing out crazyara on my bot!
