### ISSUE TITLE
Not able to execute ClassicAra 0.9.5.post0

### ISSUE THREAD

**Issue by aochoam** [QueensGambit/CrazyAra#158]
Hello,

**Issue:** I am not able to execute the new https://github.com/QueensGambit/CrazyAra/releases/tag/0.9.5.post0.

**Symptom:** When executing Multiara.exe, I get the error  **The code execution cannot proceed because interference_engine.dll was not found. Reinstalling the program may fix this problem.**

![image](https://user-images.githubusercontent.com/49724452/132104819-13514900-00f6-42b1-b884-e494e3989077.png)

**My Installation folder:**   C:\Arena\Engines\ClassicAra

[.]                                       [..]
inference_engine_legacy.dll               inference_engine_lp_transformations.dll
inference_engine_onnx_reader.dll          inference_engine_preproc.dll
inference_engine_transformations.dll      Intel_Software_Development_Products.txt
libhwloc-5.dll                            libprotobuf.dll
MKLDNNPlugin.dll                          [model]
MultiAra.exe                              multiara_logo_high.png
MultiDevicePlugin.dll                     myriadPlugin.dll
myriad_compile.exe                        myriad_perfcheck.exe
ngraph.dll                                ngraphd.dll
onnx_importer.dll                         onnx_importerd.dll
onnx_proto.dll                            OpenVino_EULA.txt
openvino_redist.txt
              22 archivos     74.688.971 bytes
               3 dirs  88.729.923.584 bytes libres

Thank you.

Regards,
Arturo Ochoa.

**Comment by QueensGambit** [comment]
Hi @aochoam ,

for me the file **interference_engine.dll** is included within the release.
Did you delete any files after downloading the release?
This is the file  tree after I unzipped the windows version.

```python
CrazyAra_ClassicAra_MultiAra_0.9.5.post0_Win_OpenVino
├── AutoPlugin.dll
├── cache.json
├── ClassicAra.exe
├── classicara_logo_small.png
├── clDNNPlugin.dll
├── CRAZYARA_AUTHORS
├── CrazyAra.exe
├── CRAZYARA_LICENSE
├── crazyara_logo_small.png
├── gna.dll
├── GNAPlugin.dll
├── hddl_perfcheck.exe
├── HDDLPlugin.dll
├── HeteroPlugin.dll
├── inference_engine_c_api.dll
├── inference_engine.dll
├── inference_engine_ir_reader.dll
├── inference_engine_legacy.dll
├── inference_engine_lp_transformations.dll
├── inference_engine_onnx_reader.dll
├── inference_engine_preproc.dll
├── inference_engine_transformations.dll
├── Intel_Software_Development_Products.txt
├── libhwloc-5.dll
├── libprotobuf.dll
├── MKLDNNPlugin.dll
├── model
│   ├── ClassicAra
│   │   └── chess
│   │       ├── model-1.19414-0.585-0513-v3.0-fixed-bsize-16.onnx
│   │       ├── model-1.19414-0.585-0513-v3.0-fixed-bsize-1.onnx
│   │       └── model-1.19414-0.585-0513-v3.0-fixed-bsize-8.onnx
│   ├── CrazyAra
│   │   └── readme.txt
│   └── MultiAra
│       └── readme.txt
├── MultiAra.exe
├── multiara_logo_high.png
├── MultiDevicePlugin.dll
├── myriad_compile.exe
├── myriad_perfcheck.exe
├── myriadPlugin.dll
├── ngraphd.dll
├── ngraph.dll
├── onnx_importerd.dll
├── onnx_importer.dll
├── onnx_proto.dll
├── OpenVino_EULA.txt
├── openvino_redist.txt
├── OpenVINOsupport.txt
├── pcie-ma2x8x.elf
├── plugins.xml
├── tbbbind.dll
├── tbb.dll
├── tbbmalloc.dll
├── tbb_preview.dll
└── usb-ma2x8x.mvcmd

5 directories, 52 files
```

**Comment by aochoam** [comment]
Hello,

Thanks. You are right. Probably, I messed up with the installation.

Let's see how it goes with the setup.

Regards, Arturo Ochoa.
