### ISSUE TITLE
TensorRT Memory Free Error

### ISSUE THREAD

**Issue by QueensGambit** [QueensGambit/CrazyAra#161]
You may run into 
```python
Unexpected Internal Error: [virtualMemoryBuffer.cpp::~StdVirtualMemoryBufferImpl::121] Error Code 1: Cuda Runtime (driver shutting down)
```
after building with the trt-files with TensorRT >= 8.2.0.6 and quitting the engine.
However, using the TensorRT files should still works as expected.

**Comment by AdanWang** [comment]
I think you may need to destory the engine.

**Comment by QueensGambit** [comment]
Thanks for the hint. I think this is because the TensorRT API was changed for TensorRT >= 8.2.0.6 and a lot of methods were marked as deprecated.

**Comment by brevity2021** [comment]
Hi, I was building an unrelated project using TensorRT (java application using TensorRT execution provider in ONNX) and encountered the exact same issue. I found this via the search engine results. Wonder did you end up solving this problem?

**Comment by QueensGambit** [comment]
@brevity2021 Yes, it looks like the problem has been resolved in https://github.com/QueensGambit/CrazyAra/pull/164.
Thank you for reminder.
