### ISSUE TITLE
Hello, can you make a Chinese chess release

### ISSUE THREAD

**Issue by shuangqiao999** [QueensGambit/CrazyAra#163]
I like Chinese chess very much. Chinese chess is very popular. If a Chinese chess engine can be released, we can play against existing Chinese chess engines

**Comment by QueensGambit** [comment]
Thank you for raising this point again.
At the moment I have many items on my TODO list, but I will give it a higher priority.

**Comment by cjssh1002** [comment]
I have previously mentioned about Korean chess, please consider the priority of Korean chess as well.~!!

**Comment by QueensGambit** [comment]
Thanks for the reminder.
I'll keep it in mind. As far as I know, there are no big data sets of professionals available for Janggi,
Therefore we would rely on learning from zero-knowledge.

**Comment by cjssh1002** [comment]
> 알림 주셔서 감사합니다. 명심하겠습니다. 내가 아는 한 장기에 사용할 수 있는 전문가의 빅 데이터 세트가 없으므로 영지식에서 배우는 것에 의존할 것입니다.

I will give you my janggi PGN. (About 50,000 to 100,000 games)

**Comment by QueensGambit** [comment]
An experimental version for Xiangqi is now available in [release 0.9.9](https://github.com/QueensGambit/CrazyAra/releases/tag/0.9.9).
However, the neural network was only trained on a small data set of human expert games so far.

**Comment by shuangqiao999** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
