### ISSUE TITLE
用图形界面加载XiangqiAra.exe不走棋

### ISSUE THREAD

**Issue by ziyue123456789** [QueensGambit/CrazyAra#175]
作者你好，我是一个中国象棋爱好者，我下载了Aras_0.9.9_Win_OpenVino.zip和XiangqiAra-sl-model.zip，然后我将XiangqiAra-sl-model.zip解压缩，按照步骤，将里面的全部模型文件移动到了model/<engine-name>/<variant>文件夹中，然后我用图形界面程序加载了XiangqiAra.exe程序，之后我运行我的象棋软件，发现软件没有走棋，是我的方法有问题吗？希望作者能够帮帮我

**Comment by ziyue123456789** [comment]
![image](https://user-images.githubusercontent.com/65974744/168251145-6ba92103-ec68-4d3b-8b2c-a82630f02376.png)

**Comment by QueensGambit** [comment]
Hello @ziyue123456789 ,
_XiangqiAra_ follows the UCI-protocol.
This means you can use _XiangqiAra_ from the command line like this.
```python
setoption name uci_variant value xiangqi
isready
go
```

This will result in the following output:
```python
$ ./XiangqiAra

                                  _                                           
                   _..           /   ._   _.  _        /\   ._   _.           
                 .' _ `\         \_  |   (_|  /_  \/  /--\  |   (_|           
                /  /e)-,\                         /                           
               /  |  ,_ |                    __    __    __    __             
              /   '-(-.)/          bw     8 /__////__////__////__////         
            .'--.   \  `                 7 ////__////__////__////__/          
           /    `\   |                  6 /__////__////__////__////           
         /`       |  / /`\.-.          5 ////__////__////__////__/            
       .'        ;  /  \_/__/         4 /__////__////__////__////             
     .'`-'_     /_.'))).-` \         3 ////__////__////__////__/              
    / -'_.'---;`'-))).-'`\_/        2 /__////__////__////__////               
   (__.'/   /` .'`                 1 ////__////__////__////__/                
    (_.'/ /` /`                       a  b  c  d  e  f  g  h                  
      _|.' /`                                                                 
jgs.-` __.'|  Developers: Johannes Czech, Moritz Willig, Alena Beyer          
    .-'||  |  Source-Code: QueensGambit/CrazyAra (GPLv3-License)              
       \_`/   Inspiration: A0-paper by Silver, Hubert, Schrittwieser et al.   
              ASCII-Art: Joan G. Stark, Chappell, Burton                      

info string Error: Given variant ' chess ' is invalid
setoption name uci_variant value xiangqi
info string variant Xiangqi startpos rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RNBAKABNR w - - 0 1
isready
info string onnx file: model/XiangqiAra/xiangqi/model-1.51615-0.508-1414-bsize-1.onnx
info string deserialize engine: model/XiangqiAra/xiangqi/model-bsize1-fp16-0.trt
info string Input representation:  0.0.0
info string inputDims: (1, 28, 10, 9)
info string valueOutputDims: (1, 1)
info string policyOutputDims: (1, 4500)
info string No auxiliary outputs detected.
info string onnx file: model/XiangqiAra/xiangqi/model-1.51615-0.508-1414-bsize-16.onnx
info string deserialize engine: model/XiangqiAra/xiangqi/model-bsize16-fp16-0.trt
info string Input representation:  0.0.0
info string onnx file: model/XiangqiAra/xiangqi/model-1.51615-0.508-1414-bsize-16.onnx
info string deserialize engine: model/XiangqiAra/xiangqi/model-bsize16-fp16-0.trt
info string Input representation:  0.0.0
info string inputDims: (16, 28, 10, 9)
info string valueOutputDims: (16, 1)
info string policyOutputDims: (16, 4500)
info string No auxiliary outputs detected.
readyok
go
info string create new tree
info string hash size:  0
info string run mcts search
info string No limit specification given, setting movetime[ms] to 1000
info depth 17 seldepth 22 multipv 1 score cp 72 nodes 10235 nps 10024 tbhits 0 time 1021 pv c4c5 b8c8 h3e3 c10e8 h1g3 c7c6 i1h1 c6c5 b1a3 i10i9 a1b1 i9d9 d1e2 d10e9 b3d3 h10i8 h1h5
info string rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RNBAKABNR w - - 0 1
bestmove c4c5
info string apply move to tree
```

For more information on how you can use _XiangqiAra_ from the command line, you can visit the wiki-page: [command line usage](https://github.com/QueensGambit/CrazyAra/wiki/Command-Line-Usage)


As for the GUI you can e.g. use [LiGround](https://github.com/ml-research/liground), [CuteChess](https://github.com/cutechess/cutechess/pull/565) or any other GUI with UCI support.

**Comment by piladinmew** [comment]
> 你好@ziyue123456789, _象棋阿拉_遵循UCI-protocol。 这意味着您可以像这样从命令行使用_XiangqiAra 。_
> 
> ```python
> setoption name uci_variant value xiangqi
> isready
> go
> ```
> 
> 这将导致以下输出：
> 
> ```python
> $ ./XiangqiAra
> 
>                                   _                                           
>                    _..           /   ._   _.  _        /\   ._   _.           
>                  .' _ `\         \_  |   (_|  /_  \/  /--\  |   (_|           
>                 /  /e)-,\                         /                           
>                /  |  ,_ |                    __    __    __    __             
>               /   '-(-.)/          bw     8 /__////__////__////__////         
>             .'--.   \  `                 7 ////__////__////__////__/          
>            /    `\   |                  6 /__////__////__////__////           
>          /`       |  / /`\.-.          5 ////__////__////__////__/            
>        .'        ;  /  \_/__/         4 /__////__////__////__////             
>      .'`-'_     /_.'))).-` \         3 ////__////__////__////__/              
>     / -'_.'---;`'-))).-'`\_/        2 /__////__////__////__////               
>    (__.'/   /` .'`                 1 ////__////__////__////__/                
>     (_.'/ /` /`                       a  b  c  d  e  f  g  h                  
>       _|.' /`                                                                 
> jgs.-` __.'|  Developers: Johannes Czech, Moritz Willig, Alena Beyer          
>     .-'||  |  Source-Code: QueensGambit/CrazyAra (GPLv3-License)              
>        \_`/   Inspiration: A0-paper by Silver, Hubert, Schrittwieser et al.   
>               ASCII-Art: Joan G. Stark, Chappell, Burton                      
> 
> info string Error: Given variant ' chess ' is invalid
> setoption name uci_variant value xiangqi
> info string variant Xiangqi startpos rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RNBAKABNR w - - 0 1
> isready
> info string onnx file: model/XiangqiAra/xiangqi/model-1.51615-0.508-1414-bsize-1.onnx
> info string deserialize engine: model/XiangqiAra/xiangqi/model-bsize1-fp16-0.trt
> info string Input representation:  0.0.0
> info string inputDims: (1, 28, 10, 9)
> info string valueOutputDims: (1, 1)
> info string policyOutputDims: (1, 4500)
> info string No auxiliary outputs detected.
> info string onnx file: model/XiangqiAra/xiangqi/model-1.51615-0.508-1414-bsize-16.onnx
> info string deserialize engine: model/XiangqiAra/xiangqi/model-bsize16-fp16-0.trt
> info string Input representation:  0.0.0
> info string onnx file: model/XiangqiAra/xiangqi/model-1.51615-0.508-1414-bsize-16.onnx
> info string deserialize engine: model/XiangqiAra/xiangqi/model-bsize16-fp16-0.trt
> info string Input representation:  0.0.0
> info string inputDims: (16, 28, 10, 9)
> info string valueOutputDims: (16, 1)
> info string policyOutputDims: (16, 4500)
> info string No auxiliary outputs detected.
> readyok
> go
> info string create new tree
> info string hash size:  0
> info string run mcts search
> info string No limit specification given, setting movetime[ms] to 1000
> info depth 17 seldepth 22 multipv 1 score cp 72 nodes 10235 nps 10024 tbhits 0 time 1021 pv c4c5 b8c8 h3e3 c10e8 h1g3 c7c6 i1h1 c6c5 b1a3 i10i9 a1b1 i9d9 d1e2 d10e9 b3d3 h10i8 h1h5
> info string rnbakabnr/9/1c5c1/p1p1p1p1p/9/9/P1P1P1P1P/1C5C1/9/RNBAKABNR w - - 0 1
> bestmove c4c5
> info string apply move to tree
> ```
> 
> 有关如何从命令行使用_XiangqiAra_的更多信息，您可以访问 wiki 页面：[命令行使用](https://github.com/QueensGambit/CrazyAra/wiki/Command-Line-Usage)
> 
> 至于 GUI，您可以使用[LiGround](https://github.com/ml-research/liground)、[CuteChess](https://github.com/cutechess/cutechess/pull/565)或任何其他支持 UCI 的 GUI。

I spent a lot of time trying to find out why the engine didn't work.
Then I realized that the problem might be ARAS_ 0.9.9_ Win_ OpenVino. Zip, you misspelled the name of the variant in the model folder
The name of the variant should be Xiangqi rather than xinagqi
hope you can fix this

**Comment by ziyue123456789** [comment]
@piladinmew 我试过了，还是不行，这这程序对于一般人来说无法使用

**Comment by QueensGambit** [comment]
Thanks for the hint @piladinmew. :+1: 
I just reuploaded the package `Aras_0.9.9_Win_OpenVino.zip`.
