### ISSUE TITLE
Wrong replay memory inclusion in fileio.py

### ISSUE THREAD

**Issue by yannikkellerde** [QueensGambit/CrazyAra#189]
In _include_data_from_replay_memory in fileio.py the goal is to include random files from the most recent replay memory given by fraction_for_selection. For this, we get the filenames with os.listdir and as the code comment suggests, after inverting, the most recent files should be on top. However, os.listdir returns files in arbitrary order (see https://docs.python.org/3/library/os.html#os.listdir). I think the confusion comes from listdir being ordered by date on windows, but on my linux machine it definitely is not.
https://github.com/QueensGambit/CrazyAra/blob/5ec10bdf5dd87a14bd0f3ed4fba5296b2f3201c8/engine/src/rl/fileio.py#L132-L135
I'd suggest explicitly sorting via os.path.getmtime:
`file_names.sort(key=lambda x:os.path.getmtime(os.path.join(self.train_dir_archive,x)))`

**Comment by QueensGambit** [comment]
Hello @yannikkellerde ,
thanks a lot for your issue submission. :)
I plan to open a new discord server for _CrazyAra_ soon.
Currently, _CrazyAra_ is in a severe buggy state and there a lot of issues still to do.
I think I would break down if I try to tackle all of them on my own.
Same holds true for the _LiGround_ project.
