### ISSUE TITLE
Question about the training of the released classic ara model

### ISSUE THREAD

**Issue by YardenRokach** [QueensGambit/CrazyAra#208]
Hello,
I wanted to ask a question about the training of Classic Ara,
Was the released classic Ara binaries trained using supervised learning only, or was reinforcement learning also used?

**Comment by QueensGambit** [comment]
Hello @YardenRokach ,
the model in release [1.0.5](https://github.com/QueensGambit/CrazyAra/releases/tag/1.0.5) and [1.0.4](https://github.com/QueensGambit/CrazyAra/releases/tag/1.0.4) have been trained using supervised learning only on the [KingbaseLite2019 dataset](https://archive.org/details/KingBaseLite2019). The _ClassicAra_ binary can be built with and without reinforcement learning support using the flag [`USE_RL`](https://github.com/QueensGambit/CrazyAra/blob/master/engine/CMakeLists.txt#L6).
The released binaries don't have reinforcement learning support enabled.
