### ISSUE TITLE
Incorrect thesis title?

### ISSUE THREAD

**Issue by CGLemon** [QueensGambit/CrazyAra#210]
In the [B.Sc. Thesis](https://github.com/QueensGambit/CrazyAra#bsc-thesis) section, seems the correct title of T. Truong's thesis is ```Monte Carlo Tree Search - Minimax Hybrid in AlphaZero``` , not ```Utilizing Variance and Uncertainty in Monte-Carlo Tree Search```.

**Comment by QueensGambit** [comment]
Thank you @CGLemon for the info. I fixed it in a95a3b8!
