### ISSUE TITLE
This is not an issue

### ISSUE THREAD

**Issue by gabrielp10031978** [QueensGambit/CrazyAra#215]
Hello,

Aras_1.0.5_Win_TensorRT on what kind of hardware works?
My hardware is:
CPU: Ryzen 7 1800x
RAM: 16 Gb DDR4 @ 3000 MHz
Video: Geforce GTX 1060 6 Gb

Thanks.

**Comment by QueensGambit** [comment]
Hello @gabrielp10031978 ,
the release Aras_1.0.5_Win_TensorRT should run on your system.
Win_TensorRT stands for "Windows" with the TensorRT GPU back-end.
Do you get any errors?

**Comment by gabrielp10031978** [comment]
Thanks for your answer Mr./Ms..
The engine does not start thinking.
The executable that should be installed is ClassicAra.exe, right?
What settings should I use for my system?
Please help me.
Thanks.

**Comment by gabrielp10031978** [comment]
Thanks a lot Mr./Ms., it is working now.
