### ISSUE TITLE
Can we integrate CrazyAra in our own chess engine or use via Python code/CLI ?

### ISSUE THREAD

**Issue by shubhank008** [QueensGambit/CrazyAra#45]
I am creating my own chess engine using c#/unity and wanted to use CrazyAra as a neural network opponent AI as the ultimate difficulty compared to standard pre-programmed AI I have created (also to evaluate how good or bad my AI is).  

To do that and use/integrate CrazyAra, I wanted to use it on my server via Python as a remote AI and access it by sending and receiving moves from my engine via a API I will create.  
So basically what I want to do is, be able to access and use CrazyAra either via CLI or via Python code so I can pass it my moves (I can do both/either of algebraic or coordinate notation), CrazyAra processes it and outputs me its move made by the board and I send it back as output to my chess engine via the Python API and perform that move locally.  

So basically, my engine is running locally, CrazyAra is running remotely in linux server and being accessed by Python or CLI to provide input moves and get output moves.  

I read about the command line interface in documentation but couldn't figure how to directly pass it just moves made and get out put of moves made by Crazy.  
Being able to do this via Python would be even better.

Additionally, is it possible to contribute the games/moves data to make CrazyAra even more stronger ?

**Comment by gbtami** [comment]
You can use python-chess for UCI engine communication https://python-chess.readthedocs.io/en/latest/engine.html

**Comment by shubhank008** [comment]
> You can use python-chess for UCI engine communication https://python-chess.readthedocs.io/en/latest/engine.html

Please excuse my ignorance when asking this, but even with python-chess installed do I still use the example from docs to run CrazyAra directly (python crazyara.py) or do I use python-chess module in my python script to access crazyara via code, if is so any docs or example available to do so ?  
I also saw the part about using crazyara with cutechess and as cutechess also provides a CLI, is it same as using python-chess ?

**Comment by QueensGambit** [comment]
The command `python crazyara.py` is for older python versions ([CrazyAra **<=0.5.1**](https://github.com/QueensGambit/CrazyAra/releases/tag/0.5.1)).

Newer versions are built as an executable and can be run via `CrazyAra.exe` or `./CrazyAra`.
The engine supports the [universal chess interface (UCI)](http://wbec-ridderkerk.nl/html/UCIProtocol.html).
Some examples on how to use it can be found here:

* https://github.com/QueensGambit/CrazyAra/wiki/Command-Line-Usage#command-line-usage

For the reinforcement learning loop, I started _CrazyAra_ via `Popen` in python.

https://github.com/QueensGambit/CrazyAra/blob/abce1a811d9748e61edfc7f4c5b7cf96cdedf7f1/engine/src/rl/rl_loop.py#L280

This is likely not the most convenient option for your use case.
I'll post some small examples with python-chess later.

[Cute Chess](https://github.com/cutechess/cutechess) is a graphical user interface, command-line interface and a library for playing chess. Therefore, it is a great option to run engine tournaments.
I imagine that you built your own chess GUI in unity, hence python-chess should be a better option for your use case.
