### ISSUE TITLE
Why doesn't CrazyAra play only-moves instantly?

### ISSUE THREAD

**Issue by DeFilippis** [QueensGambit/CrazyAra#56]
I've been experimenting with CrazyAra recently and one thing I noticed is that it often takes a decent chunk of time contemplating a position when there is only one move available. For example, with the time control "20 moves in 10 minutes" via CuteChess, CrazyAra took 25 seconds in this position on my computer: 

<img width="823" alt="Screen Shot 2021-01-12 at 1 56 52 PM" src="https://user-images.githubusercontent.com/308931/104346329-4bb34200-54cd-11eb-8237-9c31df7b8abd.png">

I'm wondering why it takes so long to consider this position, and if there'd be a performance improvement to just immediately execute only-moves without thinking and to then think about the position on your opponent's time to save time and prevent your opponent from thinking on your time.

**Comment by QueensGambit** [comment]
Which version of _CrazyAra_ are you using?
Both the latest C++ release, _CrazyAra 0.8.0_, and the last python release, _CrazyAra 0.5.1_, have a routine to skip the search if only a single move is legal:
* https://github.com/QueensGambit/CrazyAra/blob/0.8.0/engine/src/agents/mctsagent.cpp#L291
* https://github.com/QueensGambit/CrazyAra/blob/25b62cdce71579f102f9dd55fe9e6128a309af9b/DeepCrazyhouse/src/domain/agent/player/mcts_agent.py#L285

Does this also occur if you set `Moves:` to `0` in CuteChess' game configuration window which means that both engines have 10 minutes available for the whole match?

**Comment by DeFilippis** [comment]
I'm using CrazyAra 0.8.0 for MacOS. This issue occurs even if I set `Moves` to `0` in CuteChess' game configuration window. You can test it yourself with the following FEN: `3r1rk1/ppp1Nppp/3p4/2bPp3/2Bn2b1/3P1N2/PPP2PPP/R2Q1RK1/Qbn b - - 2 11`.

With 10 minutes available for the whole match, CrazyAra is taking about 20 seconds on that move on my laptop.

**Comment by QueensGambit** [comment]
Thank you @DeFilippis for providing an example FEN and the version number.
I was able to replicate this issue.
It seems that single move are only played instantly if parts of the former tree are reused.
If _CrazyAra_ is run with a GPU back-end this is the default case (e.g. move `25. Rxg1 {+21.61/10 0.016s}` in the following PGN).


```python
[Event "My Tournament"]
[Site "?"]
[Date "2021.01.14"]
[Round "5"]
[White "CrazyAra-0.8.0-risev2-BSize-16-FP16"]
[Black "CrazyAra-0.8.0-risev2-BSize-16-FP16"]
[Result "1-0"]
[GameDuration "00:00:12"]
[GameEndTime "2021-01-14T17:12:43.380 CET"]
[GameStartTime "2021-01-14T17:12:30.854 CET"]
[PlyCount "59"]
[TimeControl "10+0.1"]
[Variant "crazyhouse"]

1. e4 {book} c5 {book} 2. Nf3 {book} e6 {book} 3. d4 {book} cxd4 {book}
4. Nxd4 {book} Nc6 {book} 5. Nc3 {book} Qc7 {book} 6. Be3 {book} a6 {book}
7. Bd3 {book} b5 {book} 8. O-O {book} Bb7 {book} 9. Qe2 {book} Nf6 {book}
10. f4 {book} Nxd4 {book} 11. Bxd4 {+5.61/22 0.31s} N@h5 {-5.14/21 0.30s}
12. e5 {+7.22/23 0.31s} P@g3 {-6.66/22 0.31s} 13. P@b6 {+6.95/18 0.31s}
Qc6 {-6.70/16 0.31s} 14. N@e4 {+8.75/21 0.32s} Nxe4 {-8.32/21 0.32s}
15. Bxe4 {+9.89/22 0.32s} Qc5 {-9.32/18 0.32s} 16. N@c7+ {+10.80/20 0.32s}
Kd8 {-10.30/18 0.32s} 17. Bxc5 {+11.29/17 0.33s} Bxc5+ {-10.97/20 0.32s}
18. Kh1 {+11.62/17 0.33s} gxh2 {-11.30/16 0.33s} 19. Q@h4+ {+12.51/15 0.33s}
B@e7 {-12.34/16 0.33s} 20. Qexh5 {+14.43/14 0.34s} Bxh4 {-13.63/14 0.34s}
21. Qxh4+ {+15.08/11 0.34s} f6 {-14.06/13 0.34s} 22. Nxa8 {+17.41/15 0.35s}
Bxa8 {-14.23/12 0.35s} 23. R@b8+ {+20.80/13 0.35s} N@c8 {-20.64/12 0.35s}
24. exf6 {+28.11/12 0.35s} Q@g1+ {-23.34/11 0.35s} 25. Rxg1 {+21.61/10 0.016s}
hxg1=Q+ {-24.10/10 0.36s} 26. Rxg1 {+18.77/8 0.004s} R@h2+ {-21.27/8 0.36s}
27. Kxh2 {+36.09/8 0.41s} Bxg1+ {-28.24/7 0.37s} 28. Kxg1 {+35.80/6 0.42s}
P@f2+ {-25.28/5 0.37s} 29. Qxf2 {+41.35/5 0.43s} R@e8 {-75.09/2 0.38s}
30. Q@c7# {+M1/1 0.014s, White mates} 1-0
```

I plan to fix this bug for the upcoming release.

---

The current NN-backend for Mac also doesn't use Intel-MKL yet which should roughly double the number of nodes per second.
Moreover, I managed to calibrate INT8 weights for the Intel-MKL backend which will be provided in the next release.
