### ISSUE TITLE
At signs @ in PV string flagged as illegal

### ISSUE THREAD

**Issue by brianprichardson** [QueensGambit/CrazyAra#73]
D:\Cutechess-cli>cutechess-cli -each tc=0:10+1.0 restart=on -engine conf=CrazyAra.exe_0.8.0 -engine conf=SF11 -games 12000 -wait 1000 -ratinginterval 10 -tb E:/syzygy;E:/syzygy-7 -tbpieces 7 -openings file=D:/Cutechess-cli/book_3moves_cp25-49_13580pos.pgn start=1 -repeat -concurrency 1 -pgnout CrazyAra.exe_0.8.0_v_128x10-SF11.pgn min fi
Started game 1 of 12000 (CrazyAra.exe_0.8.0 vs SF11)
Warning: Illegal PV move P@g4 from CrazyAra.exe_0.8.0 (0)
Warning: PV: Bg5 Bb4+ Nbd2 dxc4 Rc1 b5 a4 h6 Bxf6 Qxf6 e3 P@g4
Warning: Illegal PV move B@d5 from CrazyAra.exe_0.8.0 (0)
Warning: PV: e3 Nc6 Nbd2 Ne4 Bxe7 Qxe7 Be2 Nxd2 Nxd2 dxc4 O-O B@d5
Warning: Illegal PV move B@f5 from CrazyAra.exe_0.8.0 (0)
Warning: PV: Bxf6 Bxf6 Nbd2 Nc6 Be2 O-O O-O B@f5
Warning: Illegal PV move B@f5 from CrazyAra.exe_0.8.0 (0)
Warning: PV: Nbd2 Nc6 Be2 O-O O-O B@f5
Warning: Illegal PV move B@f5 from CrazyAra.exe_0.8.0 (0)
Warning: PV: Be2 Nc6 O-O B@f5
Warning: Illegal PV move N@h5 from CrazyAra.exe_0.8.0 (0)
Warning: PV:  N@h5
Finished game 1 (CrazyAra.exe_0.8.0 vs SF11): 0-1 {White makes an illegal move: N@h5}

**Comment by QueensGambit** [comment]
Hello @brianprichardson ,
you need to use the _ClassicAra_ executalble if you want to let it play standard chess.
The @ notation indicates a dropping move in crazyhouse.

**Comment by brianprichardson** [comment]
Apologies...
