### ISSUE TITLE
CrazyAra_ClassicAra_0.9.0 Losses on Time

### ISSUE THREAD

**Issue by brianprichardson** [QueensGambit/CrazyAra#74]
See attached PGN file with 4 time loss games.
Time control 0:10+1.0, so 1 second increment
GPU is 2080ti
cutechess-cli command:
`cutechess-cli -each tc=0:10+1.0 restart=on -engine conf=CrazyAra_ClassicAra_0.9.0 -engine conf=SF7 -games 12000 -wait 1000 -ratinginterval 10 -tb E:/syzygy;E:/syzygy-7 -tbpieces 7 -openings file=D:/Cutechess-cli/book_3moves_cp25-49_13580pos.pgn start=1 -repeat -concurrency 1 -pgnout CrazyAra_ClassicAra_0.9.0_v_SF7.pgn fi`

[CrazyAra_ClassicAra_0.9.0_v_SF7.zip](https://github.com/QueensGambit/CrazyAra/files/6266308/CrazyAra_ClassicAra_0.9.0_v_SF7.zip)

**Comment by QueensGambit** [comment]
Thank you for the information @brianprichardson .
You can try to increase the UCI-Option `Move_Overhead`.
By default it is set to 20ms.

**Comment by brianprichardson** [comment]
With move overhead at 50 still one time loss so far in this match
`# PLAYER                   :  RATING  ERROR  POINTS  PLAYED   (%)    W    D    L  D(%)  CFS(%)
1 SF5                      :       8     43    89.5     175    51   65   49   61    28      65
2 CrazyAra_ClassicAra_0.9.0:       0   ----    85.5     175    49   61   49   65    28     ---
`
SF5 3243 Elo CCRL on 1 CPU
2080ti GPU

**Comment by brianprichardson** [comment]
With move overhead 50 one loss on time so far in this match
 PLAYER                   :   RATING  ERROR  POINTS  PLAYED   (%)    W    D    L  D(%)  CFS(%)
1 SF5                      :       8     43    89.5     175    51   65   49   61    28      65
2 CrazyAra_ClassicAra_0.9.0:       0   ----    85.5     175    49   61   49   65    28     ---

time control 0:10+1
2080ti GPU
SF5 3243 Elo CCRL on 1 CPU

**Comment by QueensGambit** [comment]
Thanks for the update.
I mostly tested with adjudication based on cp-eval.
This could be the reason why I haven't encountered this problem.

In the meant time, you can also disable the time-manager and enforce a fixed time per move using the UCI option `Fixed_Movetime`[ms] or `Nodes` in combination with `Simulations`.
This will disable the time management all together but also reduces playing strength.

**Comment by QueensGambit** [comment]
Hopefully fixed now.

Before commit 8066f80:
```python
>>position fen 1r4k1/1r3bb1/7p/Q4Pp1/2p3P1/1P1p4/P1P5/2KR3R b - - 2 29
>>go wtime 100 btime 100 winc 1000 binc 1000
>>position fen 1r4k1/1r3bb1/7p/Q4Pp1/2p3P1/1P1p4/P1P5/2KR3R b - - 2 29
>>go wtime 100 btime 100 winc 1000 binc 1000
info string reuse the full tree
info string 69747 nodes of former tree will be reused
info string run mcts search
info string Increase search time
info string Increase search time
info depth 11 seldepth 28 multipv 1 score cp -9 nodes 101912 nps 19601 tbhits 0 time 1641 pv b7b5 a5a7 b5b7 a7a6 b7b6 a6a7 b6b7 a7a6 b7b6 a6a7 b6b7
info string 1r4k1/1r3bb1/7p/Q4Pp1/2p3P1/1P1p4/P1P5/2KR3R b - - 2 29
bestmove b7b5
```

-> Time limit was exceeded.

After commit 8066f80:

```python
>>position fen 1r4k1/1r3bb1/7p/Q4Pp1/2p3P1/1P1p4/P1P5/2KR3R b - - 2 29
>>go wtime 100 btime 100 winc 1000 binc 1000
>>position fen 1r4k1/1r3bb1/7p/Q4Pp1/2p3P1/1P1p4/P1P5/2KR3R b - - 2 29
>>go wtime 100 btime 100 winc 1000 binc 1000
info string reuse the full tree
info string 62364 nodes of former tree will be reused
info string run mcts search
info depth 9 seldepth 26 multipv 1 score cp -7 nodes 74930 nps 19665 tbhits 0 time 639 pv b7b5 a5a6 b5b6 a6a5 b6b5 a5a6 b5b6 a6a5 b6b5
info string 1r4k1/1r3bb1/7p/Q4Pp1/2p3P1/1P1p4/P1P5/2KR3R b - - 2 29
bestmove b7b5
```

-> The time limit was respected.
