### ISSUE TITLE
ClassicAra .84 crashing on isready

### ISSUE THREAD

**Issue by masterkni666** [QueensGambit/CrazyAra#75]
I placed the ClassicAra v.84 in the same folder as v.90 and it crashes on isready. v.90 starts up fine. Have a 3080

**Comment by QueensGambit** [comment]
Yes, I forgot to add this note.
The _ClassicAra_ and _CrazyAra 0.8.0_ binary expect the `Model_Directory` to be `model/` while release 0.9.0 expects it to be `model/chess` and `model/crazyhouse`  instead.

There are two ways to fix this problem.
* 1. You manually set the  `Model_Directory` before calling `isready`
```setoption name Model_Directory value model/chess```
* 2. You move the files from `model/chess` into `model/`.

**Comment by masterkni666** [comment]
working, thanks
