### ISSUE TITLE
documentation on UCI options

### ISSUE THREAD

**Issue by masterkni666** [QueensGambit/CrazyAra#76]
any place on descriptions of UCI options? the one on github is missing alot and --help in commandline does nothing.
Im trying to use my second GPU and i see First_Device_ID but not sure if thats the right option. Thanks and sorry for all the issues

**Comment by QueensGambit** [comment]
No, worries. I think a lot of people have similar problems or questions and benefit from your issues.

The UCI Options are documented in the Wiki pages:
* https://github.com/QueensGambit/CrazyAra/wiki/Engine-settings

However, the documentation is currently out-of sync with the current release.
I'll update it soon.

---

I agree that more info on how to use multiple GPU would be nice.
Multi-GPU Support has already been integreated in (#33).

> The option Device_ID has been replaced by First_Device_ID and Last_Device_ID.
This way CrazyAra will use all GPUs with a device id of:
First_Device_ID <= Device ID <= Last_Device_ID.
All GPUs use the same precision backend (e.g. float32, float16, int8) and batch size.

**Comment by masterkni666** [comment]
im just using each GPU for their own exclusive matches. However setting First and Last device ID to 1 crashes. Second GPU works with lc0 so not sure if there is a problem

**Comment by QueensGambit** [comment]
You need to run the `isready` process again, preferably from the command line, if you want to use a different GPU.
However, this needs to done only once.

**Comment by masterkni666** [comment]
im using cutechess so dont think that is an option

**Comment by QueensGambit** [comment]
>  Oh is it to generate another trt file?
Correct.
As you may use two different types of GPUs, they require a different trt-file.

**Comment by masterkni666** [comment]
awesome, thanks

**Comment by QueensGambit** [comment]
The documentation on the UCI options has been updated in the wiki-pages(https://github.com/QueensGambit/CrazyAra/wiki/Engine-settings).

Adding an additional `--help` flag sounds can be a good addition for future releases.
