### ISSUE TITLE
Log File

### ISSUE THREAD

**Issue by brianprichardson** [QueensGambit/CrazyAra#78]
In trying to gather more information regarding #74, games were playing with the Log_File option.
Unfortunately, it looks like the log file is overwritten with each new game.
Many engines either append to the existing log file or create a new one with a unique name sequence.
Either option would be more helpful, IMO.
Thank you for sharing you work.

**Comment by QueensGambit** [comment]
The `Log_File` UCI option is currently broken. Thanks for pointing this out.
At the moment you, need to rely on the tournament GUI to store all the UCI logs.
